---
- name: Install Load Balancer
  hosts: loadbalancer
  gather_facts: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install nginx
      apt:
        name:
          - nginx
          - libnginx-mod-stream

    - name: Create load balancer configuration file
      template:
        src: ../../templates/ubuntu/loadbalancer/99-loadbalancer.conf
        dest: /etc/nginx/modules-enabled/99-loadbalancer.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start NGINX server
      systemd:
        name: nginx
        enabled: yes
        state: restarted
